<script src="{{asset('Assets/asset_front/js/modernizr.js')}}"></script>
<script src="{{asset('Assets/asset_front/js/html5shiv.js')}}"></script>
<script src="{{asset('Assets/asset_front/js/respond.min.js')}}"></script>
<script src="{{asset('Assets/asset_front/js/jquery-2.1.1.js')}}"></script>
<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="{{asset('Assets/asset_front/js/gmaps.js')}}"></script>
<script src="{{asset('Assets/asset_front/js/smoothscroll.js')}}"></script>
<script src="{{asset('Assets/asset_front/js/bootstrap.min.js')}}"></script>
<script src="{{asset('Assets/asset_front/js/custom.js')}}"></script>